### ISSUE TITLE
Feature: add reaction to a comment

### ISSUE THREAD

**Issue by rwieruch** [the-road-to-graphql/react-graphql-github-apollo#3]
It should be possible to add a reaction to comments/issues by using the addReaction mutation of the GraphQL GitHub API.

**Comment by mnaeem95** [comment]
@rwieruch  Can I pick this up? I think it'll be a good first issue :)

**Comment by rwieruch** [comment]
Sure! 👍

**Comment by rwieruch** [comment]
See https://github.com/rwieruch/react-graphql-github-apollo/pull/6 in case we want to add reactions to comments as well. I just think we need to find a neat place for the reactions.

**Comment by rwieruch** [comment]
Comments are added in https://github.com/rwieruch/react-graphql-github-apollo/pull/6 now.

**Comment by rwieruch** [comment]
@mnaeem95 are you working this? Otherwise, someone else might want to pick it up or can help you with it.
